name: "Release"

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: ChanTsune/release-with-commit@v2.0.1
        with:
          regexp: "Release (\\d+([.]\\d+)*)\n*((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "$1"
          body: "$3"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    outputs:
      created: ${{ steps.create_release.outputs.created }}

  publish:
    needs: release
    if: ${{ needs.release.outputs.created == 'true' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            publish_command: publishAllPublicationsToBintrayRepository
          - os: macos-latest
            publish_command: publishAppleToBintrayRepository
          - os: windows-latest
            publish_command: publishMingwX64PublicationToBintrayRepository publishMingwX86PublicationToBintrayRepository
    name: publish
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: run publication
        run: ./gradlew clean ${{ matrix.publish_command }}
    env:
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
